//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientUnitSubscription
    {
        public long Id { get; set; }
        public int ClientId { get; set; }
        public int OrderId { get; set; }
        public string InvoiceNumber { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<int> CardId { get; set; }
        public string PONumber { get; set; }
        public string CheckNumbers { get; set; }
        public string FrontImage { get; set; }
        public string BackImage { get; set; }
        public string AccountingNotes { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.DateTime PaymentDueDate { get; set; }
        public Nullable<System.DateTime> PaymentReceivedDate { get; set; }
        public string Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<int> AddedByType { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<decimal> PricePerMonth { get; set; }
        public string AuthorizeNetSubscriptionId { get; set; }
        public string ClientUnitIds { get; set; }
        public string CheckAmounts { get; set; }
        public Nullable<System.DateTime> PaidUntilDate { get; set; }
        public Nullable<int> TotalUnits { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<decimal> OriginalPricePerMonth { get; set; }
        public Nullable<bool> IsAdjusted { get; set; }
        public string AdjustComment { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ClientPaymentMethod ClientPaymentMethod { get; set; }
        public virtual Order Order { get; set; }
    }
}
