//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeWorkarea
    {
        public long Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public short PriorityArea { get; set; }
        public Nullable<int> AreaId { get; set; }
    
        public virtual AreaMaster AreaMaster { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
