//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FailedBillingHistory
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string ServiceCaseNumber { get; set; }
        public string PackageName { get; set; }
        public string BillingType { get; set; }
        public Nullable<decimal> OriginalAmount { get; set; }
        public Nullable<decimal> PurchasedAmount { get; set; }
        public Nullable<decimal> PartnerSalesCommisionAmount { get; set; }
        public string BillingAddress { get; set; }
        public int BillingCity { get; set; }
        public Nullable<int> BillingState { get; set; }
        public string BillingZipcode { get; set; }
        public string BillingPhoneNumber { get; set; }
        public string BillingMobileNumber { get; set; }
        public string TransactionId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public string failcode { get; set; }
        public string faildesc { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual City City { get; set; }
        public virtual Client Client { get; set; }
        public virtual ClientUnit ClientUnit { get; set; }
        public virtual State State { get; set; }
    }
}
