//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestedService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestedService()
        {
            this.RequestedServiceBridges = new HashSet<RequestedServiceBridge>();
            this.RequestedServiceUnits = new HashSet<RequestedServiceUnit>();
        }
    
        public long Id { get; set; }
        public string ServiceCaseNumber { get; set; }
        public int ClientId { get; set; }
        public int AddressId { get; set; }
        public string PurposeOfVisit { get; set; }
        public string ServiceRequestedTime { get; set; }
        public System.DateTime ServiceRequestedOn { get; set; }
        public string Notes { get; set; }
        public Nullable<long> ServiceId { get; set; }
        public int AddedBy { get; set; }
        public int AddedByType { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> UpdatedByType { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<int> DeletedByType { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ClientAddress ClientAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestedServiceBridge> RequestedServiceBridges { get; set; }
        public virtual Role Role { get; set; }
        public virtual Role Role1 { get; set; }
        public virtual Role Role2 { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestedServiceUnit> RequestedServiceUnits { get; set; }
    }
}
