//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceReportImage
    {
        public int Id { get; set; }
        public long ServiceReportId { get; set; }
        public string ServiceImage { get; set; }
    
        public virtual ServiceReport ServiceReport { get; set; }
    }
}
