//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceAttemptCount
    {
        public int Id { get; set; }
        public long ServiceId { get; set; }
        public string AttemtFailReason { get; set; }
        public Nullable<System.DateTime> AttemptDate { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
