//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    
    public partial class uspa_Units_GetUnitsByModelNumber_Result1
    {
        public int Id { get; set; }
        public string ModelNumber { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public string MFGMonthYear { get; set; }
        public string ManufactureBrand { get; set; }
        public string UnitTon { get; set; }
        public int Thermostat { get; set; }
        public int Refrigerant { get; set; }
        public string ElectricalService { get; set; }
        public int Breaker { get; set; }
        public int Compressor { get; set; }
        public int Capacitor { get; set; }
        public int Contactor { get; set; }
        public int Filterdryer { get; set; }
        public int Defrostboard { get; set; }
        public int Relay { get; set; }
        public int TXVValve { get; set; }
        public int ReversingValve { get; set; }
        public int BlowerMotor { get; set; }
        public int Condensingfanmotor { get; set; }
        public int Inducerdraftmotor { get; set; }
        public int Transformer { get; set; }
        public int Controlboard { get; set; }
        public int Limitswitch { get; set; }
        public int Ignitor { get; set; }
        public int Gasvalve { get; set; }
        public int Pressureswitch { get; set; }
        public int Flamesensor { get; set; }
        public int Rolloutsensor { get; set; }
        public int Doorswitch { get; set; }
        public int Ignitioncontrolboard { get; set; }
        public int Coil { get; set; }
        public int Misc { get; set; }
        public string MaxBreaker { get; set; }
    }
}
